builders:
  - script
triggers:
  cron: "@weekly"
environment_variables:
  NEO4J_VERSION: "latest"
pre_build_script:
  - "docker pull neo4j:${NEO4J_VERSION}"
script:
  - "python3.7 -m venv venv"
  - ". venv/bin/activate"
  - "pip install -U setuptools wheel mypy"
  - "python setup.py testing"
  - "pip freeze"
  - "python setup.py test"
  - "python setup.py sdist bdist_wheel --universal"
publish_over_ssh:
  - pypi.sunet.se
clean_workspace: true
